plan:
- category: bench
  current_max: 192
  name: Bench (Davey Style)
  notes:
  - build up to single heavy set
  training_day: 1
  weeks:
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 1x5@85%
    set_inol: 0.3333333333333333
    volume: '5'
    week: 1
    weight: '163.2'
    weight_rounded: '163.0'
  - amrap_target: 4
    exercise_inol: 0.3333333333333333
    scheme: 1x4@88%
    set_inol: 0.3333333333333333
    volume: '4'
    week: 2
    weight: '168.96'
    weight_rounded: '169.0'
  - amrap_target: 3
    exercise_inol: 0.3
    scheme: 1x3@90%
    set_inol: 0.3
    volume: '3'
    week: 3
    weight: '172.8'
    weight_rounded: '173.0'
  - amrap_target: 2
    exercise_inol: 0.2857142857142857
    scheme: 1x2@93%
    set_inol: 0.2857142857142857
    volume: '2'
    week: 4
    weight: '178.56'
    weight_rounded: '178.5'
- category: bench
  current_max: 194
  name: Dips
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '126.1'
    weight_rounded: '126.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '135.8'
    weight_rounded: '136.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '145.5'
    weight_rounded: '146.0'
  - amrap_target: 7
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '155.2'
    weight_rounded: '155.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '164.9'
    weight_rounded: '165.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '174.6'
    weight_rounded: '175.0'
- category: bench
  current_max: 190
  name: Close Grip (Max)
  notes:
  - pause everything
  - dont panic
  training_day: 5
  weeks:
  - amrap_target: 6
    exercise_inol: 0.125
    scheme: 1x2@84%
    set_inol: 0.125
    volume: '2'
    week: 1
    weight: '159.6'
    weight_rounded: '160.0'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '163.4'
    weight_rounded: '163.0'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 3
    weight: '167.2'
    weight_rounded: '167.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 4
    weight: '171.0'
    weight_rounded: '171.0'
- category: Snatch
  current_max: 88
  name: Snatch
  notes:
  - pause at bottom
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '57.2'
    weight_rounded: '57.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '61.6'
    weight_rounded: '62.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '66.0'
    weight_rounded: '66.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '70.4'
    weight_rounded: '70.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '74.8'
    weight_rounded: '75.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '79.2'
    weight_rounded: '79.0'
- category: Squat
  current_max: 90
  name: Front Squat
  notes:
  - Use straps
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Squat
  current_max: 60
  name: Overhead Squat
  notes:
  - Paused at bottom
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.4
    scheme: 2x7@65%
    set_inol: 0.2
    volume: '14'
    week: 1
    weight: '39.0'
    weight_rounded: '39.0'
  - amrap_target: 13
    exercise_inol: 0.4
    scheme: 6x2@70%
    set_inol: 0.06666666666666667
    volume: '12'
    week: 2
    weight: '42.0'
    weight_rounded: '42.0'
  - amrap_target: 10
    exercise_inol: 0.4
    scheme: 5x2@75%
    set_inol: 0.08
    volume: '10'
    week: 3
    weight: '45.0'
    weight_rounded: '45.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '48.0'
    weight_rounded: '48.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '51.0'
    weight_rounded: '51.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '54.0'
    weight_rounded: '54.0'
- category: Clean
  current_max: 94
  name: Clean
  notes:
  - Smooth
  - Straps?
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '61.1'
    weight_rounded: '61.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '65.8'
    weight_rounded: '66.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '70.5'
    weight_rounded: '71.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '75.2'
    weight_rounded: '75.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '79.9'
    weight_rounded: '80.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '84.6'
    weight_rounded: '85.0'
- category: Squat
  current_max: 105
  name: Squat
  notes:
  - Use straps
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '68.25'
    weight_rounded: '68.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '73.5'
    weight_rounded: '74.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '78.75'
    weight_rounded: '79.0'
  - amrap_target: 8
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '89.25'
    weight_rounded: '89.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '94.5'
    weight_rounded: '95.0'
summary:
  workload_all:
    1: 3.801190476190476
    2: 4.742857142857143
    3: 4.466666666666667
    4: 3.785714285714286
    5: 2.8
    6: 2.4
  workload_category:
    Clean:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6000000000000001
      5: 0.4666666666666667
      6: 0.4
    Snatch:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6000000000000001
      5: 0.4666666666666667
      6: 0.4
    Squat:
      1: 1.6
      2: 2.0
      3: 1.84
      4: 1.6
      5: 1.4666666666666668
      6: 1.2000000000000002
    bench:
      1: 1.0583333333333333
      2: 1.1428571428571428
      3: 1.1866666666666668
      4: 0.9857142857142858
      5: 0.4
      6: 0.4
  workload_daily:
    1:
      1: 0.3333333333333333
      2: 0.3333333333333333
      3: 0.3
      4: 0.2857142857142857
      5: 0
      6: 0
    2:
      1: 1.1714285714285715
      2: 1.6
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.8
    3:
      1: 1.0
      2: 1.0666666666666667
      3: 1.12
      4: 0.9
      5: 0.8
      6: 0.8
    4:
      1: 1.1714285714285715
      2: 1.6
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.8
    5:
      1: 0.125
      2: 0.14285714285714285
      3: 0.16666666666666666
      4: 0.2
      5: 0
      6: 0
