plan:
- category: bench
  current_max: 188
  name: Bench (Volume)
  notes:
  - pause everything
  training_day: 1
  weeks:
  - amrap_target: 14
    exercise_inol: 0.9375
    scheme: 3x10@68%
    set_inol: 0.3125
    volume: '30'
    week: 1
    weight: '127.84'
    weight_rounded: '128.0'
  - amrap_target: 13
    exercise_inol: 1.0
    scheme: 3x10@70%
    set_inol: 0.3333333333333333
    volume: '30'
    week: 2
    weight: '131.6'
    weight_rounded: '132.0'
  - amrap_target: 12
    exercise_inol: 1.0714285714285714
    scheme: 3x10@72%
    set_inol: 0.35714285714285715
    volume: '30'
    week: 3
    weight: '135.36'
    weight_rounded: '135.0'
  - amrap_target: 8
    exercise_inol: 0.6818181818181818
    scheme: 3x5@78%
    set_inol: 0.22727272727272727
    volume: '15'
    week: 4
    weight: '146.64'
    weight_rounded: '147.0'
  - amrap_target: 7
    exercise_inol: 0.75
    scheme: 3x5@80%
    set_inol: 0.25
    volume: '15'
    week: 5
    weight: '150.4'
    weight_rounded: '150.0'
  - amrap_target: 7
    exercise_inol: 0.8333333333333334
    scheme: 3x5@82%
    set_inol: 0.2777777777777778
    volume: '15'
    week: 6
    weight: '154.16'
    weight_rounded: '154.0'
  - amrap_target: 3
    exercise_inol: 0.8999999999999999
    scheme: 3x3@90%
    set_inol: 0.3
    volume: '9'
    week: 7
    weight: '169.2'
    weight_rounded: '169.0'
  - amrap_target: 3
    exercise_inol: 0.75
    scheme: 3x2@92%
    set_inol: 0.25
    volume: '6'
    week: 8
    weight: '172.96'
    weight_rounded: '173.0'
- category: bench
  current_max: 187
  name: Dips
  notes:
  - Easy block
  training_day: 3
  weeks:
  - amrap_target: 13
    exercise_inol: 0.6
    scheme: 2x9@70%
    set_inol: 0.3
    volume: '18'
    week: 1
    weight: '130.9'
    weight_rounded: '131.0'
  - amrap_target: 12
    exercise_inol: 0.5714285714285714
    scheme: 2x8@72%
    set_inol: 0.2857142857142857
    volume: '16'
    week: 2
    weight: '134.64'
    weight_rounded: '135.0'
  - amrap_target: 11
    exercise_inol: 0.6153846153846154
    scheme: 2x8@74%
    set_inol: 0.3076923076923077
    volume: '16'
    week: 3
    weight: '138.38'
    weight_rounded: '138.0'
  - amrap_target: 9
    exercise_inol: 0.5833333333333334
    scheme: 2x7@76%
    set_inol: 0.2916666666666667
    volume: '14'
    week: 4
    weight: '142.12'
    weight_rounded: '142.0'
  - amrap_target: 8
    exercise_inol: 0.6363636363636364
    scheme: 2x7@78%
    set_inol: 0.3181818181818182
    volume: '14'
    week: 5
    weight: '145.86'
    weight_rounded: '146.0'
  - amrap_target: 8
    exercise_inol: 0.6
    scheme: 2x6@80%
    set_inol: 0.3
    volume: '12'
    week: 6
    weight: '149.6'
    weight_rounded: '150.0'
  - amrap_target: 7
    exercise_inol: 0.5555555555555556
    scheme: 2x5@82%
    set_inol: 0.2777777777777778
    volume: '10'
    week: 7
    weight: '153.34'
    weight_rounded: '153.0'
  - amrap_target: 6
    exercise_inol: 0.625
    scheme: 2x5@84%
    set_inol: 0.3125
    volume: '10'
    week: 8
    weight: '157.08'
    weight_rounded: '157.0'
- category: Snatch
  current_max: 98
  name: Snatch
  notes:
  - pause at bottom
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '63.7'
    weight_rounded: '64.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '68.6'
    weight_rounded: '69.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '73.5'
    weight_rounded: '74.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '78.4'
    weight_rounded: '78.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '83.3'
    weight_rounded: '83.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '88.2'
    weight_rounded: '88.0'
- category: Squat
  current_max: 108
  name: Front Squat
  notes:
  - Use straps
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '70.2'
    weight_rounded: '70.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '75.6'
    weight_rounded: '76.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '81.0'
    weight_rounded: '81.0'
  - amrap_target: 7
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '86.4'
    weight_rounded: '86.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '91.8'
    weight_rounded: '92.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '97.2'
    weight_rounded: '97.0'
- category: Clean
  current_max: 105
  name: Clean
  notes:
  - Smooth
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '68.25'
    weight_rounded: '68.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '73.5'
    weight_rounded: '74.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '78.75'
    weight_rounded: '79.0'
  - amrap_target: 8
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '89.25'
    weight_rounded: '89.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '94.5'
    weight_rounded: '95.0'
- category: Squat
  current_max: 135
  name: Squat
  notes:
  - Dont get hurt
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '87.75'
    weight_rounded: '88.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '94.5'
    weight_rounded: '95.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '101.25'
    weight_rounded: '101.0'
  - amrap_target: 8
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '108.0'
    weight_rounded: '108.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '114.75'
    weight_rounded: '115.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '121.5'
    weight_rounded: '122.0'
- category: Snatch
  current_max: 90
  name: Hang Snatch
  notes:
  - pause at bottom
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Snatch
  current_max: 105
  name: Snatch Pull
  notes:
  - slow and smooth
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '68.25'
    weight_rounded: '68.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '73.5'
    weight_rounded: '74.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '78.75'
    weight_rounded: '79.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '89.25'
    weight_rounded: '89.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '94.5'
    weight_rounded: '95.0'
- category: Clean
  current_max: 90
  name: Power Clean
  notes:
  - Speed
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Clean
  current_max: 75
  name: RDL
  notes:
  - Smooth
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '48.75'
    weight_rounded: '49.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '52.5'
    weight_rounded: '53.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '56.25'
    weight_rounded: '56.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '60.0'
    weight_rounded: '60.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '63.75'
    weight_rounded: '64.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '67.5'
    weight_rounded: '68.0'
- category: Clean
  current_max: 120
  name: Sumo Pull
  notes:
  - Smooth
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '78.0'
    weight_rounded: '78.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '90.0'
    weight_rounded: '90.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '96.0'
    weight_rounded: '96.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '102.0'
    weight_rounded: '102.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '108.0'
    weight_rounded: '108.0'
summary:
  workload_all:
    1: 5.880357142857145
    2: 7.7714285714285705
    3: 6.966813186813187
    4: 5.665151515151517
    5: 5.053030303030302
    6: 4.533333333333332
    7: 1.4555555555555555
    8: 1.375
  workload_category:
    Clean:
      1: 1.7714285714285711
      2: 2.6
      3: 2.16
      4: 1.7999999999999998
      5: 1.4666666666666666
      6: 1.3
      7: 0
      8: 0
    Snatch:
      1: 1.3714285714285712
      2: 2.0
      3: 1.68
      4: 1.4
      5: 1.1333333333333333
      6: 1.0
      7: 0
      8: 0
    Squat:
      1: 1.2000000000000002
      2: 1.6
      3: 1.44
      4: 1.2
      5: 1.0666666666666667
      6: 0.8
      7: 0
      8: 0
    bench:
      1: 1.5375
      2: 1.5714285714285714
      3: 1.6868131868131868
      4: 1.2651515151515151
      5: 1.3863636363636362
      6: 1.4333333333333333
      7: 1.4555555555555555
      8: 1.375
  workload_daily:
    1:
      1: 2.1089285714285717
      2: 2.6
      3: 2.5114285714285716
      4: 1.8818181818181818
      5: 1.75
      6: 1.6333333333333333
      7: 0.8999999999999999
      8: 0.75
    2:
      1: 1.1714285714285715
      2: 1.6
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.8
      7: 0
      8: 0
    3:
      1: 1.4
      2: 1.7714285714285716
      3: 1.5753846153846154
      4: 1.3833333333333333
      5: 1.303030303030303
      6: 1.2000000000000002
      7: 0.5555555555555556
      8: 0.625
    4:
      1: 1.2
      2: 1.8000000000000003
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.9000000000000001
      7: 0
      8: 0
