plan:
- category: bench
  current_max: 57
  name: Bench (Double)
  notes:
  - pause everything (mississippi style)
  - dont panic
  training_day: 1
  weeks:
  - amrap_target: 5
    exercise_inol: 0.13333333333333333
    scheme: 1x2@85%
    set_inol: 0.13333333333333333
    volume: '2'
    week: 1
    weight: '48.45'
    weight_rounded: '48.5'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '49.02'
    weight_rounded: '49.0'
  - amrap_target: 4
    exercise_inol: 0.15384615384615385
    scheme: 1x2@87%
    set_inol: 0.15384615384615385
    volume: '2'
    week: 3
    weight: '49.59'
    weight_rounded: '49.5'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 4
    weight: '50.16'
    weight_rounded: '50.0'
  - amrap_target: 4
    exercise_inol: 0.18181818181818182
    scheme: 1x2@89%
    set_inol: 0.18181818181818182
    volume: '2'
    week: 5
    weight: '50.73'
    weight_rounded: '50.5'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 6
    weight: '51.3'
    weight_rounded: '51.5'
- category: bench
  current_max: 57
  name: Bench (Volume)
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '37.05'
    weight_rounded: '37.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '39.9'
    weight_rounded: '40.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '42.75'
    weight_rounded: '43.0'
  - amrap_target: 7
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '45.6'
    weight_rounded: '45.5'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '48.45'
    weight_rounded: '48.5'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '51.3'
    weight_rounded: '51.5'
- category: bench
  current_max: 57
  name: Dips
  notes:
  - pause everything
  - dont panic
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '37.05'
    weight_rounded: '37.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '39.9'
    weight_rounded: '40.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '42.75'
    weight_rounded: '43.0'
  - amrap_target: 7
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '45.6'
    weight_rounded: '46.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '48.45'
    weight_rounded: '48.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '51.3'
    weight_rounded: '51.0'
summary:
  workload_all:
    1: 1.3333333333333335
    2: 1.4761904761904763
    3: 1.5938461538461537
    4: 1.1666666666666665
    5: 0.9818181818181818
    6: 1.0
  workload_category:
    bench:
      1: 1.3333333333333335
      2: 1.4761904761904763
      3: 1.5938461538461537
      4: 1.1666666666666665
      5: 0.9818181818181818
      6: 1.0
  workload_daily:
    1:
      1: 0.7333333333333334
      2: 0.8095238095238095
      3: 0.8738461538461538
      4: 0.6666666666666666
      5: 0.5818181818181818
      6: 0.6000000000000001
    3:
      1: 0.6000000000000001
      2: 0.6666666666666666
      3: 0.72
      4: 0.5
      5: 0.4
      6: 0.4
