plan:
- category: bench
  current_max: 192
  name: Bench (Double)
  notes:
  - pause everything (mississippi style)
  - dont panic
  training_day: 1
  weeks:
  - amrap_target: 5
    exercise_inol: 0.13333333333333333
    scheme: 1x2@85%
    set_inol: 0.13333333333333333
    volume: '2'
    week: 1
    weight: '163.2'
    weight_rounded: '163.0'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '165.12'
    weight_rounded: '165.0'
  - amrap_target: 4
    exercise_inol: 0.15384615384615385
    scheme: 1x2@87%
    set_inol: 0.15384615384615385
    volume: '2'
    week: 3
    weight: '167.04'
    weight_rounded: '167.0'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 4
    weight: '168.96'
    weight_rounded: '169.0'
  - amrap_target: 4
    exercise_inol: 0.18181818181818182
    scheme: 1x2@89%
    set_inol: 0.18181818181818182
    volume: '2'
    week: 5
    weight: '170.88'
    weight_rounded: '171.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 6
    weight: '172.8'
    weight_rounded: '173.0'
- category: bench
  current_max: 192
  name: Bench (Volume)
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '124.8'
    weight_rounded: '125.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '134.4'
    weight_rounded: '134.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '144.0'
    weight_rounded: '144.0'
  - amrap_target: 7
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '153.6'
    weight_rounded: '154.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '163.2'
    weight_rounded: '163.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '172.8'
    weight_rounded: '173.0'
- category: bench
  current_max: 140
  name: Bands
  notes:
  - pause everything
  - dont panic
  - Speed of the chest
  - Squeeze triceps/try to accelerate all the way to lockout
  training_day: 3
  weeks:
  - amrap_target: 30
    exercise_inol: 0.36
    scheme: 6x3@50%
    set_inol: 0.06
    volume: '18'
    week: 1
    weight: '70.0'
    weight_rounded: '70.0'
  - amrap_target: 29
    exercise_inol: 0.36734693877551017
    scheme: 6x3@51%
    set_inol: 0.061224489795918366
    volume: '18'
    week: 2
    weight: '71.4'
    weight_rounded: '71.0'
  - amrap_target: 28
    exercise_inol: 0.375
    scheme: 6x3@52%
    set_inol: 0.0625
    volume: '18'
    week: 3
    weight: '72.8'
    weight_rounded: '73.0'
  - amrap_target: 27
    exercise_inol: 0.3829787234042553
    scheme: 6x3@53%
    set_inol: 0.06382978723404255
    volume: '18'
    week: 4
    weight: '74.2'
    weight_rounded: '74.0'
  - amrap_target: 26
    exercise_inol: 0.3913043478260869
    scheme: 6x3@54%
    set_inol: 0.06521739130434782
    volume: '18'
    week: 5
    weight: '75.6'
    weight_rounded: '76.0'
  - amrap_target: 25
    exercise_inol: 0.4
    scheme: 6x3@55%
    set_inol: 0.06666666666666667
    volume: '18'
    week: 6
    weight: '77.0'
    weight_rounded: '77.0'
- category: bench
  current_max: 192
  name: Dips
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '124.8'
    weight_rounded: '125.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '134.4'
    weight_rounded: '134.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '144.0'
    weight_rounded: '144.0'
  - amrap_target: 7
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '153.6'
    weight_rounded: '154.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '163.2'
    weight_rounded: '163.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '172.8'
    weight_rounded: '173.0'
- category: bench
  current_max: 185
  name: Close Grip (Max)
  notes:
  - pause everything
  - dont panic
  training_day: 5
  weeks:
  - amrap_target: 5
    exercise_inol: 0.13333333333333333
    scheme: 1x2@85%
    set_inol: 0.13333333333333333
    volume: '2'
    week: 1
    weight: '157.25'
    weight_rounded: '157.0'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '159.1'
    weight_rounded: '159.0'
  - amrap_target: 4
    exercise_inol: 0.15384615384615385
    scheme: 1x2@87%
    set_inol: 0.15384615384615385
    volume: '2'
    week: 3
    weight: '160.95'
    weight_rounded: '161.0'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 4
    weight: '162.8'
    weight_rounded: '163.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 5
    weight: '166.5'
    weight_rounded: '167.0'
  - amrap_target: 3
    exercise_inol: 0.25
    scheme: 1x2@92%
    set_inol: 0.25
    volume: '2'
    week: 6
    weight: '170.2'
    weight_rounded: '170.0'
- category: Snatch
  current_max: 80
  name: Snatch
  notes:
  - pause at bottom
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '52.0'
    weight_rounded: '52.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '56.0'
    weight_rounded: '56.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '60.0'
    weight_rounded: '60.0'
  - amrap_target: 8
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '64.0'
    weight_rounded: '64.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '68.0'
    weight_rounded: '68.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '72.0'
    weight_rounded: '72.0'
- category: Clean
  current_max: 82
  name: Clean
  notes:
  - Smooth
  - Straps?
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '53.3'
    weight_rounded: '53.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '57.4'
    weight_rounded: '57.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '61.5'
    weight_rounded: '62.0'
  - amrap_target: 7
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '65.6'
    weight_rounded: '66.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '69.7'
    weight_rounded: '70.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '73.8'
    weight_rounded: '74.0'
summary:
  workload_all:
    1: 2.9695238095238095
    2: 3.5863945578231293
    3: 3.5626923076923074
    4: 2.916312056737589
    5: 2.506455862977602
    6: 2.4499999999999997
  workload_category:
    Clean:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6
      5: 0.4666666666666667
      6: 0.4
    Snatch:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6
      5: 0.4666666666666667
      6: 0.4
    bench:
      1: 1.8266666666666667
      2: 1.9863945578231292
      3: 2.122692307692308
      4: 1.7163120567375887
      5: 1.5731225296442688
      6: 1.65
  workload_daily:
    1:
      1: 1.3047619047619048
      2: 1.6095238095238096
      3: 1.5938461538461537
      4: 1.2666666666666666
      5: 1.0484848484848484
      6: 1.0
    3:
      1: 0.9600000000000001
      2: 1.0340136054421767
      3: 1.095
      4: 0.8829787234042553
      5: 0.7913043478260869
      6: 0.8
    4:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6
      5: 0.4666666666666667
      6: 0.4
    5:
      1: 0.13333333333333333
      2: 0.14285714285714285
      3: 0.15384615384615385
      4: 0.16666666666666666
      5: 0.2
      6: 0.25
