plan:
- category: bench
  current_max: 195
  name: Bench (531)
  notes:
  - Assistance pull downs
  training_day: 1
  weeks:
  - exercise_inol: 1.2739174640259885
    exercise_volume: 56
    exercise_work: 5694.375
    sets:
    - amrap_target: 53
      count: 2
      intensity: '36'
      reps: 8
      scheme: 2x8@36%
      set_inol: 0.125
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 29
      count: 1
      intensity: '51'
      reps: 5
      scheme: 1x5@51%
      set_inol: 0.10204081632653061
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 21
      count: 1
      intensity: 58.5
      reps: 5
      scheme: 1x5@58.5%
      set_inol: 0.12048192771084337
      volume: 5
      weight: 114.07499999999999
      weight_rounded: 115.0
      work: 570.375
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 131.625
      weight_rounded: 132.5
      work: 658.125
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 5
      scheme: 1x5@76.5%
      set_inol: 0.2127659574468085
      volume: 5
      weight: 149.175
      weight_rounded: 150.0
      work: 745.875
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 20
      scheme: 1x20@54%
      set_inol: 0.43478260869565216
      volume: 20
      weight: 105
      weight_rounded: 105.0
      work: 2100
    week: 1
  - exercise_inol: 1.1329421000882263
    exercise_volume: 50
    exercise_work: 4983.6
    sets:
    - amrap_target: 53
      count: 2
      intensity: '36'
      reps: 8
      scheme: 2x8@36%
      set_inol: 0.125
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 29
      count: 1
      intensity: '51'
      reps: 5
      scheme: 1x5@51%
      set_inol: 0.10204081632653061
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 18
      count: 1
      intensity: 63
      reps: 3
      scheme: 1x3@63%
      set_inol: 0.08108108108108109
      volume: 3
      weight: 122.85
      weight_rounded: 122.5
      work: 368.54999999999995
    - amrap_target: 12
      count: 1
      intensity: 72
      reps: 3
      scheme: 1x3@72%
      set_inol: 0.10714285714285714
      volume: 3
      weight: 140.4
      weight_rounded: 140.0
      work: 421.20000000000005
    - amrap_target: 7
      count: 1
      intensity: 81
      reps: 3
      scheme: 1x3@81%
      set_inol: 0.15789473684210525
      volume: 3
      weight: 157.95000000000002
      weight_rounded: 157.5
      work: 473.85
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 20
      scheme: 1x20@54%
      set_inol: 0.43478260869565216
      volume: 20
      weight: 105
      weight_rounded: 105.0
      work: 2100
    week: 2
  - exercise_inol: 1.1899262495251695
    exercise_volume: 52
    exercise_work: 5232.375
    sets:
    - amrap_target: 53
      count: 2
      intensity: '36'
      reps: 8
      scheme: 2x8@36%
      set_inol: 0.125
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 29
      count: 1
      intensity: '51'
      reps: 5
      scheme: 1x5@51%
      set_inol: 0.10204081632653061
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 18
      count: 1
      intensity: '62'
      reps: 2
      scheme: 1x2@62%
      set_inol: 0.05263157894736842
      volume: 2
      weight: 120
      weight_rounded: 120.0
      work: 240
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 131.625
      weight_rounded: 132.5
      work: 658.125
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 3
      scheme: 1x3@76.5%
      set_inol: 0.1276595744680851
      volume: 3
      weight: 149.175
      weight_rounded: 150.0
      work: 447.52500000000003
    - amrap_target: 5
      count: 1
      intensity: 85.5
      reps: 1
      scheme: 1x1@85.5%
      set_inol: 0.06896551724137931
      volume: 1
      weight: 166.725
      weight_rounded: 167.5
      work: 166.725
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 20
      scheme: 1x20@54%
      set_inol: 0.43478260869565216
      volume: 20
      weight: 105
      weight_rounded: 105.0
      work: 2100
    week: 3
  - exercise_inol: 0.7125123517786561
    exercise_volume: 35
    exercise_work: 3416.25
    sets:
    - amrap_target: 53
      count: 1
      intensity: 36
      reps: 5
      scheme: 1x5@36%
      set_inol: 0.078125
      volume: 5
      weight: 70.2
      weight_rounded: 70.0
      work: 351.0
    - amrap_target: 37
      count: 1
      intensity: 45
      reps: 5
      scheme: 1x5@45%
      set_inol: 0.09090909090909091
      volume: 5
      weight: 87.75
      weight_rounded: 87.5
      work: 438.75
    - amrap_target: 26
      count: 1
      intensity: 54
      reps: 5
      scheme: 1x5@54%
      set_inol: 0.10869565217391304
      volume: 5
      weight: 105.30000000000001
      weight_rounded: 105.0
      work: 526.5
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 20
      scheme: 1x20@54%
      set_inol: 0.43478260869565216
      volume: 20
      weight: 105
      weight_rounded: 105.0
      work: 2100
    week: 4
summary:
  workload_all:
    1:
      inol: 1.2739174640259885
      volume: 56
      work: 5694.375
    2:
      inol: 1.1329421000882263
      volume: 50
      work: 4983.6
    3:
      inol: 1.1899262495251695
      volume: 52
      work: 5232.375
    4:
      inol: 0.7125123517786561
      volume: 35
      work: 3416.25
  workload_category:
    bench:
      1:
        inol: 1.2739174640259885
        volume: 56
        work: 5694.375
      2:
        inol: 1.1329421000882263
        volume: 50
        work: 4983.6
      3:
        inol: 1.1899262495251695
        volume: 52
        work: 5232.375
      4:
        inol: 0.7125123517786561
        volume: 35
        work: 3416.25
  workload_daily:
    1:
      1:
        inol: 1.2739174640259885
        volume: 56
        work: 5694.375
      2:
        inol: 1.1329421000882263
        volume: 50
        work: 4983.6
      3:
        inol: 1.1899262495251695
        volume: 52
        work: 5232.375
      4:
        inol: 0.7125123517786561
        volume: 35
        work: 3416.25
