plan:
- category: bench
  current_max: 202.5
  name: Bench (531)
  notes:
  - Assistance incline dumbells
  training_day: 1
  weeks:
  - exercise_inol: 1.6125371008439262
    exercise_volume: 86
    exercise_work: 7295.3125
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 8
      scheme: 2x8@35%
      set_inol: 0.12307692307692308
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 31
      count: 1
      intensity: '49'
      reps: 5
      scheme: 1x5@49%
      set_inol: 0.09803921568627451
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 21
      count: 1
      intensity: 58.5
      reps: 5
      scheme: 1x5@58.5%
      set_inol: 0.12048192771084337
      volume: 5
      weight: 118.46249999999999
      weight_rounded: 117.5
      work: 592.3125
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 136.6875
      weight_rounded: 137.5
      work: 683.4375
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 5
      scheme: 1x5@76.5%
      set_inol: 0.2127659574468085
      volume: 5
      weight: 154.9125
      weight_rounded: 155.0
      work: 774.5625
    - amrap_target: 53
      count: 1
      intensity: '36'
      reps: 50
      scheme: 1x50@36%
      set_inol: 0.78125
      volume: 50
      weight: 72.5
      weight_rounded: 72.5
      work: 3625.0
    week: 1
  - exercise_inol: 1.4715617369061642
    exercise_volume: 80
    exercise_work: 6557.2
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 8
      scheme: 2x8@35%
      set_inol: 0.12307692307692308
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 31
      count: 1
      intensity: '49'
      reps: 5
      scheme: 1x5@49%
      set_inol: 0.09803921568627451
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 18
      count: 1
      intensity: 63
      reps: 3
      scheme: 1x3@63%
      set_inol: 0.08108108108108109
      volume: 3
      weight: 127.575
      weight_rounded: 127.5
      work: 382.725
    - amrap_target: 12
      count: 1
      intensity: 72
      reps: 3
      scheme: 1x3@72%
      set_inol: 0.10714285714285714
      volume: 3
      weight: 145.79999999999998
      weight_rounded: 145.0
      work: 437.4
    - amrap_target: 7
      count: 1
      intensity: 81
      reps: 3
      scheme: 1x3@81%
      set_inol: 0.15789473684210525
      volume: 3
      weight: 164.025
      weight_rounded: 165.0
      work: 492.07500000000005
    - amrap_target: 53
      count: 1
      intensity: '36'
      reps: 50
      scheme: 1x50@36%
      set_inol: 0.78125
      volume: 50
      weight: 72.5
      weight_rounded: 72.5
      work: 3625.0
    week: 2
  - exercise_inol: 1.5246947952006171
    exercise_volume: 82
    exercise_work: 6806.3125
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 8
      scheme: 2x8@35%
      set_inol: 0.12307692307692308
      volume: 16
      weight: 70
      weight_rounded: 70.0
      work: 1120
    - amrap_target: 31
      count: 1
      intensity: '49'
      reps: 5
      scheme: 1x5@49%
      set_inol: 0.09803921568627451
      volume: 5
      weight: 100
      weight_rounded: 100.0
      work: 500
    - amrap_target: 21
      count: 1
      intensity: '59'
      reps: 2
      scheme: 1x2@59%
      set_inol: 0.04878048780487805
      volume: 2
      weight: 120
      weight_rounded: 120.0
      work: 240
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 136.6875
      weight_rounded: 137.5
      work: 683.4375
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 3
      scheme: 1x3@76.5%
      set_inol: 0.1276595744680851
      volume: 3
      weight: 154.9125
      weight_rounded: 155.0
      work: 464.73749999999995
    - amrap_target: 5
      count: 1
      intensity: 85.5
      reps: 1
      scheme: 1x1@85.5%
      set_inol: 0.06896551724137931
      volume: 1
      weight: 173.1375
      weight_rounded: 172.5
      work: 173.1375
    - amrap_target: 53
      count: 1
      intensity: '36'
      reps: 50
      scheme: 1x50@36%
      set_inol: 0.78125
      volume: 50
      weight: 72.5
      weight_rounded: 72.5
      work: 3625.0
    week: 3
  - exercise_inol: 1.058979743083004
    exercise_volume: 65
    exercise_work: 4991.875
    sets:
    - amrap_target: 53
      count: 1
      intensity: 36
      reps: 5
      scheme: 1x5@36%
      set_inol: 0.078125
      volume: 5
      weight: 72.89999999999999
      weight_rounded: 72.5
      work: 364.49999999999994
    - amrap_target: 37
      count: 1
      intensity: 45
      reps: 5
      scheme: 1x5@45%
      set_inol: 0.09090909090909091
      volume: 5
      weight: 91.125
      weight_rounded: 90.0
      work: 455.625
    - amrap_target: 26
      count: 1
      intensity: 54
      reps: 5
      scheme: 1x5@54%
      set_inol: 0.10869565217391304
      volume: 5
      weight: 109.35000000000001
      weight_rounded: 110.0
      work: 546.75
    - amrap_target: 53
      count: 1
      intensity: '36'
      reps: 50
      scheme: 1x50@36%
      set_inol: 0.78125
      volume: 50
      weight: 72.5
      weight_rounded: 72.5
      work: 3625.0
    week: 4
- category: bench
  current_max: 202.5
  name: Close Grip (Doubles)
  notes:
  - Pull ups unassisted
  training_day: 4
  weeks:
  - exercise_inol: 0.45678228856184466
    exercise_volume: 19
    exercise_work: 1906.15
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 5
      scheme: 2x5@35%
      set_inol: 0.07692307692307693
      volume: 10
      weight: 70
      weight_rounded: 70.0
      work: 700
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 3
      scheme: 1x3@54%
      set_inol: 0.06521739130434782
      volume: 3
      weight: 110
      weight_rounded: 110.0
      work: 330
    - amrap_target: 17
      count: 1
      intensity: '64'
      reps: 2
      scheme: 1x2@64%
      set_inol: 0.05555555555555555
      volume: 2
      weight: 130
      weight_rounded: 130.0
      work: 260
    - amrap_target: 13
      count: 1
      intensity: '69'
      reps: 2
      scheme: 1x2@69%
      set_inol: 0.06451612903225806
      volume: 2
      weight: 140
      weight_rounded: 140.0
      work: 280
    - amrap_target: 6
      count: 1
      intensity: 83
      reps: 2
      scheme: 1x2@83%
      set_inol: 0.11764705882352941
      volume: 2
      weight: 168.075
      weight_rounded: 167.5
      work: 336.15
    week: 1
  - exercise_inol: 0.5589154495185351
    exercise_volume: 21
    exercise_work: 2218.3
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 5
      scheme: 2x5@35%
      set_inol: 0.07692307692307693
      volume: 10
      weight: 70
      weight_rounded: 70.0
      work: 700
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 3
      scheme: 1x3@54%
      set_inol: 0.06521739130434782
      volume: 3
      weight: 110
      weight_rounded: 110.0
      work: 330
    - amrap_target: 17
      count: 1
      intensity: '64'
      reps: 2
      scheme: 1x2@64%
      set_inol: 0.05555555555555555
      volume: 2
      weight: 130
      weight_rounded: 130.0
      work: 260
    - amrap_target: 13
      count: 1
      intensity: '69'
      reps: 2
      scheme: 1x2@69%
      set_inol: 0.06451612903225806
      volume: 2
      weight: 140
      weight_rounded: 140.0
      work: 280
    - amrap_target: 11
      count: 1
      intensity: '74'
      reps: 2
      scheme: 1x2@74%
      set_inol: 0.07692307692307693
      volume: 2
      weight: 150
      weight_rounded: 150.0
      work: 300
    - amrap_target: 5
      count: 1
      intensity: 86
      reps: 2
      scheme: 1x2@86%
      set_inol: 0.14285714285714285
      volume: 2
      weight: 174.15
      weight_rounded: 175.0
      work: 348.3
    week: 2
  - exercise_inol: 0.597876488479574
    exercise_volume: 21
    exercise_work: 2230.45
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 5
      scheme: 2x5@35%
      set_inol: 0.07692307692307693
      volume: 10
      weight: 70
      weight_rounded: 70.0
      work: 700
    - amrap_target: 26
      count: 1
      intensity: '54'
      reps: 3
      scheme: 1x3@54%
      set_inol: 0.06521739130434782
      volume: 3
      weight: 110
      weight_rounded: 110.0
      work: 330
    - amrap_target: 17
      count: 1
      intensity: '64'
      reps: 2
      scheme: 1x2@64%
      set_inol: 0.05555555555555555
      volume: 2
      weight: 130
      weight_rounded: 130.0
      work: 260
    - amrap_target: 13
      count: 1
      intensity: '69'
      reps: 2
      scheme: 1x2@69%
      set_inol: 0.06451612903225806
      volume: 2
      weight: 140
      weight_rounded: 140.0
      work: 280
    - amrap_target: 11
      count: 1
      intensity: '74'
      reps: 2
      scheme: 1x2@74%
      set_inol: 0.07692307692307693
      volume: 2
      weight: 150
      weight_rounded: 150.0
      work: 300
    - amrap_target: 4
      count: 1
      intensity: 89
      reps: 2
      scheme: 1x2@89%
      set_inol: 0.18181818181818182
      volume: 2
      weight: 180.225
      weight_rounded: 180.0
      work: 360.45
    week: 3
  - exercise_inol: 0.31654456654456653
    exercise_volume: 20
    exercise_work: 1475
    sets:
    - amrap_target: 56
      count: 2
      intensity: '35'
      reps: 5
      scheme: 2x5@35%
      set_inol: 0.07692307692307693
      volume: 10
      weight: 70
      weight_rounded: 70.0
      work: 700
    - amrap_target: 51
      count: 1
      intensity: '37'
      reps: 5
      scheme: 1x5@37%
      set_inol: 0.07936507936507936
      volume: 5
      weight: 75
      weight_rounded: 75.0
      work: 375
    - amrap_target: 45
      count: 1
      intensity: '40'
      reps: 5
      scheme: 1x5@40%
      set_inol: 0.08333333333333333
      volume: 5
      weight: 80
      weight_rounded: 80.0
      work: 400
    week: 4
- category: Squat
  current_max: 238
  name: Squat
  notes:
  - Assistance is wall ball front squats and lunges. 55/60/65/50 total reps split
    into sets where needed
  training_day: 3
  weeks:
  - exercise_inol: 0.8050387442724546
    exercise_volume: 36
    exercise_work: 4079.75
    sets:
    - amrap_target: 73
      count: 2
      intensity: '29'
      reps: 8
      scheme: 2x8@29%
      set_inol: 0.11267605633802817
      volume: 16
      weight: 70
      weight_rounded: 70
      work: 1120
    - amrap_target: 35
      count: 1
      intensity: '46'
      reps: 5
      scheme: 1x5@46%
      set_inol: 0.09259259259259259
      volume: 5
      weight: 110
      weight_rounded: 110
      work: 550
    - amrap_target: 21
      count: 1
      intensity: 58.5
      reps: 5
      scheme: 1x5@58.5%
      set_inol: 0.12048192771084337
      volume: 5
      weight: 139.23
      weight_rounded: 139
      work: 696.15
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 160.65
      weight_rounded: 161
      work: 803.25
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 5
      scheme: 1x5@76.5%
      set_inol: 0.2127659574468085
      volume: 5
      weight: 182.07
      weight_rounded: 182
      work: 910.3499999999999
    week: 1
  - exercise_inol: 0.7307300470013591
    exercise_volume: 33
    exercise_work: 3602.2400000000002
    sets:
    - amrap_target: 73
      count: 2
      intensity: '29'
      reps: 8
      scheme: 2x8@29%
      set_inol: 0.11267605633802817
      volume: 16
      weight: 70
      weight_rounded: 70
      work: 1120
    - amrap_target: 35
      count: 1
      intensity: '46'
      reps: 5
      scheme: 1x5@46%
      set_inol: 0.09259259259259259
      volume: 5
      weight: 110
      weight_rounded: 110
      work: 550
    - amrap_target: 25
      count: 1
      intensity: '55'
      reps: 3
      scheme: 1x3@55%
      set_inol: 0.06666666666666667
      volume: 3
      weight: 130
      weight_rounded: 130
      work: 390
    - amrap_target: 18
      count: 1
      intensity: 63
      reps: 3
      scheme: 1x3@63%
      set_inol: 0.08108108108108109
      volume: 3
      weight: 149.94
      weight_rounded: 150
      work: 449.82
    - amrap_target: 12
      count: 1
      intensity: 72
      reps: 3
      scheme: 1x3@72%
      set_inol: 0.10714285714285714
      volume: 3
      weight: 171.35999999999999
      weight_rounded: 171
      work: 514.0799999999999
    - amrap_target: 7
      count: 1
      intensity: 81
      reps: 3
      scheme: 1x3@81%
      set_inol: 0.15789473684210525
      volume: 3
      weight: 192.78
      weight_rounded: 193
      work: 578.34
    week: 2
  - exercise_inol: 0.7350826174909338
    exercise_volume: 33
    exercise_work: 3612.95
    sets:
    - amrap_target: 73
      count: 2
      intensity: '29'
      reps: 8
      scheme: 2x8@29%
      set_inol: 0.11267605633802817
      volume: 16
      weight: 70
      weight_rounded: 70
      work: 1120
    - amrap_target: 35
      count: 1
      intensity: '46'
      reps: 5
      scheme: 1x5@46%
      set_inol: 0.09259259259259259
      volume: 5
      weight: 110
      weight_rounded: 110
      work: 550
    - amrap_target: 25
      count: 1
      intensity: '55'
      reps: 3
      scheme: 1x3@55%
      set_inol: 0.06666666666666667
      volume: 3
      weight: 130
      weight_rounded: 130
      work: 390
    - amrap_target: 14
      count: 1
      intensity: 67.5
      reps: 5
      scheme: 1x5@67.5%
      set_inol: 0.15384615384615385
      volume: 5
      weight: 160.65
      weight_rounded: 161
      work: 803.25
    - amrap_target: 9
      count: 1
      intensity: 76.5
      reps: 3
      scheme: 1x3@76.5%
      set_inol: 0.1276595744680851
      volume: 3
      weight: 182.07
      weight_rounded: 182
      work: 546.21
    - amrap_target: 5
      count: 1
      intensity: 85.5
      reps: 1
      scheme: 1x1@85.5%
      set_inol: 0.06896551724137931
      volume: 1
      weight: 203.49
      weight_rounded: 203
      work: 203.49
    week: 3
  - exercise_inol: 0.27772974308300397
    exercise_volume: 15
    exercise_work: 1606.5
    sets:
    - amrap_target: 53
      count: 1
      intensity: 36
      reps: 5
      scheme: 1x5@36%
      set_inol: 0.078125
      volume: 5
      weight: 85.67999999999999
      weight_rounded: 86
      work: 428.4
    - amrap_target: 37
      count: 1
      intensity: 45
      reps: 5
      scheme: 1x5@45%
      set_inol: 0.09090909090909091
      volume: 5
      weight: 107.10000000000001
      weight_rounded: 107
      work: 535.5
    - amrap_target: 26
      count: 1
      intensity: 54
      reps: 5
      scheme: 1x5@54%
      set_inol: 0.10869565217391304
      volume: 5
      weight: 128.52
      weight_rounded: 129
      work: 642.6
    week: 4
summary:
  workload_all:
    1:
      inol: 2.8743581336782253
      volume: 141
      work: 13281.2125
    2:
      inol: 2.7612072334260582
      volume: 134
      work: 12377.74
    3:
      inol: 2.857653901171125
      volume: 136
      work: 12649.712500000001
    4:
      inol: 1.6532540527105744
      volume: 100
      work: 8073.375
  workload_category:
    Squat:
      1:
        inol: 0.8050387442724546
        volume: 36
        work: 4079.75
      2:
        inol: 0.7307300470013591
        volume: 33
        work: 3602.2400000000002
      3:
        inol: 0.7350826174909338
        volume: 33
        work: 3612.95
      4:
        inol: 0.27772974308300397
        volume: 15
        work: 1606.5
    bench:
      1:
        inol: 2.069319389405771
        volume: 105
        work: 9201.4625
      2:
        inol: 2.030477186424699
        volume: 101
        work: 8775.5
      3:
        inol: 2.122571283680191
        volume: 103
        work: 9036.7625
      4:
        inol: 1.3755243096275704
        volume: 85
        work: 6466.875
  workload_daily:
    1:
      1:
        inol: 1.6125371008439262
        volume: 86
        work: 7295.3125
      2:
        inol: 1.4715617369061642
        volume: 80
        work: 6557.2
      3:
        inol: 1.5246947952006171
        volume: 82
        work: 6806.3125
      4:
        inol: 1.058979743083004
        volume: 65
        work: 4991.875
    3:
      1:
        inol: 0.8050387442724546
        volume: 36
        work: 4079.75
      2:
        inol: 0.7307300470013591
        volume: 33
        work: 3602.2400000000002
      3:
        inol: 0.7350826174909338
        volume: 33
        work: 3612.95
      4:
        inol: 0.27772974308300397
        volume: 15
        work: 1606.5
    4:
      1:
        inol: 0.45678228856184466
        volume: 19
        work: 1906.15
      2:
        inol: 0.5589154495185351
        volume: 21
        work: 2218.3
      3:
        inol: 0.597876488479574
        volume: 21
        work: 2230.45
      4:
        inol: 0.31654456654456653
        volume: 20
        work: 1475
