plan:
- category: bench
  current_max: 155
  name: Bench (Volume)
  notes:
  - pause everything
  - dont panic
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.8
    scheme: 4x7@65%
    set_inol: 0.2
    volume: '28'
    week: 1
    weight: '100.75'
    weight_rounded: '101.0'
  - amrap_target: 13
    exercise_inol: 0.8333333333333333
    scheme: 5x5@70%
    set_inol: 0.16666666666666666
    volume: '25'
    week: 2
    weight: '108.5'
    weight_rounded: '109.0'
  - amrap_target: 10
    exercise_inol: 0.96
    scheme: 4x6@75%
    set_inol: 0.24
    volume: '24'
    week: 3
    weight: '116.25'
    weight_rounded: '116.0'
  - amrap_target: 7
    exercise_inol: 0.75
    scheme: 5x3@80%
    set_inol: 0.15
    volume: '15'
    week: 4
    weight: '124.0'
    weight_rounded: '124.0'
  - amrap_target: 5
    exercise_inol: 0.6666666666666666
    scheme: 5x2@85%
    set_inol: 0.13333333333333333
    volume: '10'
    week: 5
    weight: '131.75'
    weight_rounded: '132.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 6
    weight: '139.5'
    weight_rounded: '140.0'
- category: bench
  current_max: 100
  name: Strict Press
  notes:
  - pause everything
  - dont panic
  training_day: 6
  weeks:
  - amrap_target: 16
    exercise_inol: 0.8
    scheme: 4x7@65%
    set_inol: 0.2
    volume: '28'
    week: 1
    weight: '65.0'
    weight_rounded: '65.0'
  - amrap_target: 13
    exercise_inol: 0.8333333333333333
    scheme: 5x5@70%
    set_inol: 0.16666666666666666
    volume: '25'
    week: 2
    weight: '70.0'
    weight_rounded: '70.0'
  - amrap_target: 10
    exercise_inol: 0.96
    scheme: 4x6@75%
    set_inol: 0.24
    volume: '24'
    week: 3
    weight: '75.0'
    weight_rounded: '75.0'
  - amrap_target: 8
    exercise_inol: 0.75
    scheme: 5x3@80%
    set_inol: 0.15
    volume: '15'
    week: 4
    weight: '80.0'
    weight_rounded: '80.0'
  - amrap_target: 5
    exercise_inol: 0.6666666666666666
    scheme: 5x2@85%
    set_inol: 0.13333333333333333
    volume: '10'
    week: 5
    weight: '85.0'
    weight_rounded: '85.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 6
    weight: '90.0'
    weight_rounded: '90.0'
summary:
  workload_all:
    1: 1.6
    2: 1.6666666666666665
    3: 1.92
    4: 1.5
    5: 1.3333333333333333
    6: 0.4
  workload_category:
    bench:
      1: 1.6
      2: 1.6666666666666665
      3: 1.92
      4: 1.5
      5: 1.3333333333333333
      6: 0.4
  workload_daily:
    2:
      1: 0.8
      2: 0.8333333333333333
      3: 0.96
      4: 0.75
      5: 0.6666666666666666
      6: 0.2
    6:
      1: 0.8
      2: 0.8333333333333333
      3: 0.96
      4: 0.75
      5: 0.6666666666666666
      6: 0.2
