plan:
- category: bench
  current_max: 166
  name: Bench (Volume)
  notes:
  - Assistance is curls
  - week 7 is max out
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.8
    scheme: 4x7@65%
    set_inol: 0.2
    volume: '28'
    week: 1
    weight: '107.9'
    weight_rounded: '108.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 4x6@70%
    set_inol: 0.2
    volume: '24'
    week: 2
    weight: '116.2'
    weight_rounded: '116.0'
  - amrap_target: 10
    exercise_inol: 0.8
    scheme: 5x4@75%
    set_inol: 0.16
    volume: '20'
    week: 3
    weight: '124.5'
    weight_rounded: '125.0'
  - amrap_target: 7
    exercise_inol: 0.8
    scheme: 4x4@80%
    set_inol: 0.2
    volume: '16'
    week: 4
    weight: '132.8'
    weight_rounded: '133.0'
  - amrap_target: 5
    exercise_inol: 0.8
    scheme: 4x3@85%
    set_inol: 0.2
    volume: '12'
    week: 5
    weight: '141.1'
    weight_rounded: '141.0'
  - amrap_target: 3
    exercise_inol: 0.8
    scheme: 4x2@90%
    set_inol: 0.2
    volume: '8'
    week: 6
    weight: '149.4'
    weight_rounded: '149.0'
  - amrap_target: 3
    exercise_inol: 0.75
    scheme: 3x2@92%
    set_inol: 0.25
    volume: '6'
    week: 7
    weight: '152.72'
    weight_rounded: '153.0'
- category: Clean
  current_max: 175
  name: Clean Pull
  notes:
  - Assistance is 15-20 min workout
  training_day: 6
  weeks:
  - amrap_target: 16
    exercise_inol: 0.8
    scheme: 4x7@65%
    set_inol: 0.2
    volume: '28'
    week: 1
    weight: '113.75'
    weight_rounded: '114.0'
  - amrap_target: 13
    exercise_inol: 0.8333333333333333
    scheme: 5x5@70%
    set_inol: 0.16666666666666666
    volume: '25'
    week: 2
    weight: '122.5'
    weight_rounded: '122.0'
  - amrap_target: 10
    exercise_inol: 0.8
    scheme: 5x4@75%
    set_inol: 0.16
    volume: '20'
    week: 3
    weight: '131.25'
    weight_rounded: '131.0'
  - amrap_target: 7
    exercise_inol: 0.8
    scheme: 8x2@80%
    set_inol: 0.1
    volume: '16'
    week: 4
    weight: '140.0'
    weight_rounded: '140.0'
  - amrap_target: 5
    exercise_inol: 0.8
    scheme: 6x2@85%
    set_inol: 0.13333333333333333
    volume: '12'
    week: 5
    weight: '148.75'
    weight_rounded: '149.0'
  - amrap_target: 3
    exercise_inol: 0.8
    scheme: 8x1@90%
    set_inol: 0.1
    volume: '8'
    week: 6
    weight: '157.5'
    weight_rounded: '158.0'
- category: Snatch
  current_max: 90
  name: Snatch
  notes:
  - Assistance is Ab Wheel
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Clean
  current_max: 112
  name: Clean
  notes:
  - Assistance is dips
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '72.8'
    weight_rounded: '73.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '78.4'
    weight_rounded: '78.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '89.6'
    weight_rounded: '90.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '95.2'
    weight_rounded: '95.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '100.8'
    weight_rounded: '101.0'
summary:
  workload_all:
    1: 2.742857142857143
    2: 3.2333333333333334
    3: 3.04
    4: 2.8000000000000003
    5: 2.5333333333333337
    6: 2.4
    7: 0.75
  workload_category:
    Clean:
      1: 1.3714285714285714
      2: 1.6333333333333333
      3: 1.52
      4: 1.4000000000000001
      5: 1.2666666666666666
      6: 1.2000000000000002
      7: 0
    Snatch:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6000000000000001
      5: 0.4666666666666667
      6: 0.4
      7: 0
    bench:
      1: 0.8
      2: 0.8
      3: 0.8
      4: 0.8
      5: 0.8
      6: 0.8
      7: 0.75
  workload_daily:
    1:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6000000000000001
      5: 0.4666666666666667
      6: 0.4
      7: 0
    2:
      1: 0.8
      2: 0.8
      3: 0.8
      4: 0.8
      5: 0.8
      6: 0.8
      7: 0.75
    4:
      1: 0.5714285714285714
      2: 0.8
      3: 0.72
      4: 0.6000000000000001
      5: 0.4666666666666667
      6: 0.4
      7: 0
    6:
      1: 0.8
      2: 0.8333333333333333
      3: 0.8
      4: 0.8
      5: 0.8
      6: 0.8
      7: 0
