plan:
- category: bench
  current_max: 170
  name: Bench (Double)
  notes:
  - pause everything (mississippi style)
  - dont panic
  training_day: 1
  weeks:
  - amrap_target: 5
    exercise_inol: 0.13333333333333333
    scheme: 1x2@85%
    set_inol: 0.13333333333333333
    volume: '2'
    week: 1
    weight: '144.5'
    weight_rounded: '145.0'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '146.2'
    weight_rounded: '146.0'
  - amrap_target: 4
    exercise_inol: 0.15384615384615385
    scheme: 1x2@87%
    set_inol: 0.15384615384615385
    volume: '2'
    week: 3
    weight: '147.9'
    weight_rounded: '148.0'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 4
    weight: '149.6'
    weight_rounded: '150.0'
  - amrap_target: 4
    exercise_inol: 0.18181818181818182
    scheme: 1x2@89%
    set_inol: 0.18181818181818182
    volume: '2'
    week: 5
    weight: '151.3'
    weight_rounded: '151.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 6
    weight: '153.0'
    weight_rounded: '153.0'
- category: bench
  current_max: 170
  name: Bench (Volume)
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '110.5'
    weight_rounded: '111.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '119.0'
    weight_rounded: '119.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '127.5'
    weight_rounded: '128.0'
  - amrap_target: 8
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '136.0'
    weight_rounded: '136.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '144.5'
    weight_rounded: '145.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '153.0'
    weight_rounded: '153.0'
- category: bench
  current_max: 160
  name: Dips
  notes:
  - pause everything
  - dont panic
  - Do heavy double first
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '104.0'
    weight_rounded: '104.0'
  - amrap_target: 13
    exercise_inol: 0.6666666666666666
    scheme: 5x4@70%
    set_inol: 0.13333333333333333
    volume: '20'
    week: 2
    weight: '112.0'
    weight_rounded: '112.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 3x6@75%
    set_inol: 0.24
    volume: '18'
    week: 3
    weight: '120.0'
    weight_rounded: '120.0'
  - amrap_target: 8
    exercise_inol: 0.5
    scheme: 5x2@80%
    set_inol: 0.1
    volume: '10'
    week: 4
    weight: '128.0'
    weight_rounded: '128.0'
  - amrap_target: 5
    exercise_inol: 0.4
    scheme: 3x2@85%
    set_inol: 0.13333333333333333
    volume: '6'
    week: 5
    weight: '136.0'
    weight_rounded: '136.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '144.0'
    weight_rounded: '144.0'
- category: bench
  current_max: 160
  name: Close Grip (Max)
  notes:
  - pause everything
  - dont panic
  training_day: 5
  weeks:
  - amrap_target: 5
    exercise_inol: 0.13333333333333333
    scheme: 1x2@85%
    set_inol: 0.13333333333333333
    volume: '2'
    week: 1
    weight: '136.0'
    weight_rounded: '136.0'
  - amrap_target: 5
    exercise_inol: 0.14285714285714285
    scheme: 1x2@86%
    set_inol: 0.14285714285714285
    volume: '2'
    week: 2
    weight: '137.6'
    weight_rounded: '138.0'
  - amrap_target: 4
    exercise_inol: 0.15384615384615385
    scheme: 1x2@87%
    set_inol: 0.15384615384615385
    volume: '2'
    week: 3
    weight: '139.2'
    weight_rounded: '139.0'
  - amrap_target: 4
    exercise_inol: 0.16666666666666666
    scheme: 1x2@88%
    set_inol: 0.16666666666666666
    volume: '2'
    week: 4
    weight: '140.8'
    weight_rounded: '141.0'
  - amrap_target: 3
    exercise_inol: 0.2
    scheme: 1x2@90%
    set_inol: 0.2
    volume: '2'
    week: 5
    weight: '144.0'
    weight_rounded: '144.0'
  - amrap_target: 3
    exercise_inol: 0.25
    scheme: 1x2@92%
    set_inol: 0.25
    volume: '2'
    week: 6
    weight: '147.2'
    weight_rounded: '147.0'
- category: Snatch
  current_max: 102
  name: Snatch
  notes:
  - pause at bottom
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '66.3'
    weight_rounded: '66.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '71.4'
    weight_rounded: '71.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '81.6'
    weight_rounded: '82.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '86.7'
    weight_rounded: '87.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '91.8'
    weight_rounded: '92.0'
- category: Squat
  current_max: 112
  name: Front Squat
  notes:
  - Use straps
  training_day: 1
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '72.8'
    weight_rounded: '73.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '78.4'
    weight_rounded: '78.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 7
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '89.6'
    weight_rounded: '90.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '95.2'
    weight_rounded: '95.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '100.8'
    weight_rounded: '101.0'
- category: Clean
  current_max: 116
  name: Clean
  notes:
  - Smooth
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.5714285714285714
    scheme: 4x5@65%
    set_inol: 0.14285714285714285
    volume: '20'
    week: 1
    weight: '75.4'
    weight_rounded: '75.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 8x3@70%
    set_inol: 0.1
    volume: '24'
    week: 2
    weight: '81.2'
    weight_rounded: '81.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '87.0'
    weight_rounded: '87.0'
  - amrap_target: 7
    exercise_inol: 0.6000000000000001
    scheme: 6x2@80%
    set_inol: 0.1
    volume: '12'
    week: 4
    weight: '92.8'
    weight_rounded: '93.0'
  - amrap_target: 5
    exercise_inol: 0.4666666666666667
    scheme: 7x1@85%
    set_inol: 0.06666666666666667
    volume: '7'
    week: 5
    weight: '98.6'
    weight_rounded: '99.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 4x1@90%
    set_inol: 0.1
    volume: '4'
    week: 6
    weight: '104.4'
    weight_rounded: '104.0'
- category: Squat
  current_max: 155
  name: Squat
  notes:
  - Dont get hurt
  training_day: 2
  weeks:
  - amrap_target: 16
    exercise_inol: 0.6000000000000001
    scheme: 3x7@65%
    set_inol: 0.2
    volume: '21'
    week: 1
    weight: '100.75'
    weight_rounded: '101.0'
  - amrap_target: 13
    exercise_inol: 0.8
    scheme: 6x4@70%
    set_inol: 0.13333333333333333
    volume: '24'
    week: 2
    weight: '108.5'
    weight_rounded: '109.0'
  - amrap_target: 10
    exercise_inol: 0.72
    scheme: 6x3@75%
    set_inol: 0.12
    volume: '18'
    week: 3
    weight: '116.25'
    weight_rounded: '116.0'
  - amrap_target: 7
    exercise_inol: 0.6
    scheme: 4x3@80%
    set_inol: 0.15
    volume: '12'
    week: 4
    weight: '124.0'
    weight_rounded: '124.0'
  - amrap_target: 5
    exercise_inol: 0.5333333333333333
    scheme: 4x2@85%
    set_inol: 0.13333333333333333
    volume: '8'
    week: 5
    weight: '131.75'
    weight_rounded: '132.0'
  - amrap_target: 3
    exercise_inol: 0.4
    scheme: 2x2@90%
    set_inol: 0.2
    volume: '4'
    week: 6
    weight: '139.5'
    weight_rounded: '140.0'
- category: Snatch
  current_max: 90
  name: Hang Snatch
  notes:
  - pause at bottom
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Snatch
  current_max: 105
  name: Snatch Pull
  notes:
  - slow and smooth
  training_day: 3
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '68.25'
    weight_rounded: '68.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '73.5'
    weight_rounded: '74.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '78.75'
    weight_rounded: '79.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '89.25'
    weight_rounded: '89.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '94.5'
    weight_rounded: '95.0'
- category: Clean
  current_max: 90
  name: Power Clean
  notes:
  - Speed
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '58.5'
    weight_rounded: '59.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '63.0'
    weight_rounded: '63.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '67.5'
    weight_rounded: '68.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '72.0'
    weight_rounded: '72.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '76.5'
    weight_rounded: '77.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '81.0'
    weight_rounded: '81.0'
- category: Clean
  current_max: 75
  name: RDL
  notes:
  - Smooth
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '48.75'
    weight_rounded: '49.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '52.5'
    weight_rounded: '53.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '56.25'
    weight_rounded: '56.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '60.0'
    weight_rounded: '60.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '63.75'
    weight_rounded: '64.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '67.5'
    weight_rounded: '68.0'
- category: Clean
  current_max: 120
  name: Sumo Pull
  notes:
  - Smooth
  training_day: 4
  weeks:
  - amrap_target: 16
    exercise_inol: 0.39999999999999997
    scheme: 7x2@65%
    set_inol: 0.05714285714285714
    volume: '14'
    week: 1
    weight: '78.0'
    weight_rounded: '78.0'
  - amrap_target: 13
    exercise_inol: 0.6000000000000001
    scheme: 6x3@70%
    set_inol: 0.1
    volume: '18'
    week: 2
    weight: '84.0'
    weight_rounded: '84.0'
  - amrap_target: 10
    exercise_inol: 0.48
    scheme: 6x2@75%
    set_inol: 0.08
    volume: '12'
    week: 3
    weight: '90.0'
    weight_rounded: '90.0'
  - amrap_target: 8
    exercise_inol: 0.4
    scheme: 4x2@80%
    set_inol: 0.1
    volume: '8'
    week: 4
    weight: '96.0'
    weight_rounded: '96.0'
  - amrap_target: 5
    exercise_inol: 0.3333333333333333
    scheme: 5x1@85%
    set_inol: 0.06666666666666667
    volume: '5'
    week: 5
    weight: '102.0'
    weight_rounded: '102.0'
  - amrap_target: 3
    exercise_inol: 0.30000000000000004
    scheme: 3x1@90%
    set_inol: 0.1
    volume: '3'
    week: 6
    weight: '108.0'
    weight_rounded: '108.0'
summary:
  workload_all:
    1: 5.809523809523811
    2: 7.819047619047618
    3: 7.027692307692309
    4: 5.733333333333335
    5: 4.848484848484848
    6: 4.349999999999999
  workload_category:
    Clean:
      1: 1.7714285714285711
      2: 2.6
      3: 2.16
      4: 1.7999999999999998
      5: 1.4666666666666666
      6: 1.3
    Snatch:
      1: 1.3714285714285712
      2: 2.0
      3: 1.68
      4: 1.4
      5: 1.1333333333333333
      6: 1.0
    Squat:
      1: 1.2000000000000002
      2: 1.6
      3: 1.44
      4: 1.2
      5: 1.0666666666666667
      6: 0.8
    bench:
      1: 1.4666666666666668
      2: 1.619047619047619
      3: 1.7476923076923074
      4: 1.3333333333333333
      5: 1.1818181818181819
      6: 1.25
  workload_daily:
    1:
      1: 1.9047619047619049
      2: 2.40952380952381
      3: 2.3138461538461534
      4: 1.8666666666666667
      5: 1.5818181818181816
      6: 1.4
    2:
      1: 1.1714285714285715
      2: 1.6
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.8
    3:
      1: 1.4
      2: 1.8666666666666667
      3: 1.68
      4: 1.3
      5: 1.0666666666666667
      6: 1.0
    4:
      1: 1.2
      2: 1.8000000000000003
      3: 1.44
      4: 1.2000000000000002
      5: 1.0
      6: 0.9000000000000001
    5:
      1: 0.13333333333333333
      2: 0.14285714285714285
      3: 0.15384615384615385
      4: 0.16666666666666666
      5: 0.2
      6: 0.25
